# .alacritty-${ALACRITTY_PROFILE_NAME}.toml

[general]
import = [ "~/.config/alacritty/themes/ubuntu.toml" ]
working_directory = "/home/tca"
live_config_reload = true
ipc_socket = true

[env]
USE_K8S="true"

[window]
dimensions = { columns=75, lines=32 }
position = "None"
padding = { x = 1, y = 1 }
dynamic_padding = true
decorations = "Full"
opacity = 0.99
blur = true
title = "${ALACRITTY_PROFILE_NAME}"
dynamic_title = true
resize_increments = false

[scrolling]
history = 20000
multiplier = 3

[font]
normal = { family = "Ubuntu Mono", style = "Regular" }
size = 9

[colors.primary]
#foreground = "#d8d8d8"
#background = "#2C001E"
#background = "#181818"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Right", mods = "Control", action = "Hide" },
]

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
    #{ key = "T", mods = "Control|Shift", action = "CreateNewTab" }, # macos

[debug]
render_timer = false
persistent_logging = true
log_level = "Info"
