
alias alacritty_functions_list=critty_functions_list
alias alacritty_new=critty_new
alias alacritty_profiles=critty_profiles
alias alacritty_version=critty_version
alias critty_profile=critty_profiles
