---
- name: Install Alacritty from DMG
  tags: ['term']
  block:
  - name: Make tmp dir
    ansible.builtin.command: mkdir -p ./tmp/
  - name: Download Alacritty DMG
    ansible.builtin.get_url: url={{ alacritty_dmg_url }} dest=./tmp/{{ alacritty_dmg }}
  - name: Attach DMG
    ansible.builtin.command: hdiutil attach ./tmp/{{ alacritty_dmg }} -nobrowse -mountpoint ./tmp/Alacritty
  - name: Copy Alacritty App
    ansible.builtin.shell: cp -aR ./tmp/Alacritty/Alacritty.app /Applications/Alacritty.app
  - name: Detach DMG
    ansible.builtin.command: hdiutil detach ./tmp/{{ alacritty_dmg }}/
  - name: Remove tmp dir
    ansible.builtin.command: rm -R ./tmp/
  - name: Zsh Completion
    ansible.builtin.shell: |
      mkdir -p ${ZDOTDIR:-~}/.zsh_functions && \
      echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc

