---
- name: Install Packages (apt)
  become: true
  ansible.builtin.apt:
    name: '{{ alacritty_apt_packages }}'
    state: present
  tags: ['term']

- name: Ensure Rustup is installed and configured.
  become: true
  tags: ['term']
  block:
    - name: Check for Rust
      ansible.builtin.shell:
        cmd: 'source ~/.cargo/env && rustc --version'
      register: alacritty_rust_check
      ignore_errors: true
      args:
        executable: /bin/bash
    - name: Install Rust
      ansible.builtin.shell: # noqa: command-instead-of-module
        cmd: 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      when: alacritty_rust_check.rc != 0
      args:
        executable: /bin/bash
    - name: Ensure Cargo is set to stable release
      ansible.builtin.shell:
        cmd: 'source ~/.cargo/env && rustup override set stable && rustup update stable'
      args:
        executable: /bin/bash

- name: Install Alacritty
  become: true
  tags: ['term']
  block:
    - name: Git checkout alacritty
      ansible.builtin.git: # noqa: latest[git]
        repo: 'https://github.com/alacritty/alacritty.git'
        dest: '{{ alacritty_install_dir }}'
        version: '{{ alacritty_version }}'
    - name: Build Alacritty
      ansible.builtin.shell:
        cmd: 'source ~/.cargo/env && cd {{ alacritty_install_dir }} && cargo build --release'
      args:
        executable: /bin/bash
    - name: Current binary exists
      ansible.builtin.stat:
        path: '{{ alacritty_bin_path }}/alacritty'
      register: alacritty_bin_exists
    - name: Move aside current binary
      ansible.builtin.shell:
        cmd: 'mv {{ alacritty_bin_path }}/alacritty {{ alacritty_bin_path }}/alacritty-bin.{{ ansible_date_time.date }}'
      when: alacritty_bin_exists.stat.exists
    - name: Install Alacritty
      ansible.builtin.shell:
        cmd: 'cp {{ alacritty_install_dir }}/target/release/alacritty {{ alacritty_bin_path }}/'
    - name: Install logo
      ansible.builtin.shell:
        cmd: 'cp {{ alacritty_install_dir }}/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg'
    - name: Install desktop entry
      ansible.builtin.shell:
        cmd: 'desktop-file-install {{ alacritty_install_dir }}/extra/linux/Alacritty.desktop && update-desktop-database'

- name: Alacritty Terminfo
  become: true
  tags: ['terminfo']
  ansible.builtin.shell: |
    if ! infocmp alacritty; then
        tic -xe alacritty,alacritty-direct {{ alacritty_install_dir }}/extra/alacritty.info;
    fi
  args:
    executable: /bin/bash

- name: Install Alacritty Themes
  tags: ['term-themes']
  block:
    - name: Git checkout themes
      become: true
      ansible.builtin.git: # noqa: latest[git]
        repo: 'https://github.com/alacritty/alacritty-theme.git'
        dest: '{{ alacritty_themes_dir }}'
    - name: Create themes link
      ansible.builtin.file:
        src: '{{ alacritty_themes_dir }}/themes'
        dest: '~/.config/alacritty/themes'
        state: link
