---
- name: Install Alacritty
  become: true
  tags: ['term']
  block:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/alacritty/alacritty.git'
        dest: {{ alacritty_install_dir }}
        version: '{{ alacritty_version }}'
    - name: Build Alacritty
      ansible.builtin.shell: 'cd {{ alacritty_install_dir }} && cargo build --release'
    - name: Install Alacritty
      ansible.builtin.shell: 'cp {{ alacritty_install_dir }}/target/release/alacritty /usr/local/bin'
    - name: Install logo
      ansible.builtin.shell: 'cp {{ alacritty_install_dir }}/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg'
    - name: Install desktop entry
      ansible.builtin.shell: 'desktop-file-install {{ alacritty_install_dir}}/extra/linux/Alacritty.desktop && update-desktop-database'

- name: Alacritty Configuration
  tags: ['term']
  block:
    - name: Ensure target path is created
      ansible.builtin.file:
        path: '~/.config/alacritty'
        mode: '0755'
        state: directory
    - name: Copy alacritty config
      ansible.builtin.copy:
        src: "alacritty-template.toml"
        dest: "~/.config/alacritty/alacritty-template.toml"
        mode: '0644'
    - name: Copy alacritty_functions
      ansible.builtin.copy:
        src: "alacritty_functions.sh"
        dest: "~/.alacritty_functions.sh"
        mode: '0644'
    - name: Install shell completion
      ansible.builtin.shell: 'cp {{ alacritty_install_dir }}/extra/completions/alacritty.bash ~/.config/alacritty/'

- name: Install Alacritty Themes
  tags: ['term']
  block:
    - name: Git checkout
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/alacritty/alacritty-theme.git'
        dest: '{{ alacritty_themes_dir }}'
    - name: Create themes link
      ansible.builtin.file:
        src: '{{ alacritty_themes_dir }}/themes'
        dest: '~/.config/alacritty/themes'
        state: link
